---
- name: Configure DevOps Capstone Server
  hosts: webserver
  become: true

  tasks:
    - name: Install required packages
      dnf:
        name:
          - git
          - docker
        state: present
        update_cache: true

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: true

    - name: Install Docker Compose plugin
      shell: |
        mkdir -p /usr/local/lib/docker/cli-plugins
        curl -SL https://github.com/docker/compose/releases/download/v2.39.2/docker-compose-linux-x86_64 \
          -o /usr/local/lib/docker/cli-plugins/docker-compose
        chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
      args:
        creates: /usr/local/lib/docker/cli-plugins/docker-compose
